### ISSUE TITLE
Crash hitting Esc while in top-level TextArea

### ISSUE THREAD

**Issue by jawa0** [jawa0/aish3#59]
This doesn't always happen. I think it might only happen after deleting some other controls.

Traceback (most recent call last):
  File "/Users/jaba/devel/aish3/aish3.py", line 161, in <module>
    run(fullscreen=args.fullscreen, 
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/jaba/devel/aish3/aish3.py", line 121, in run
    gui.handle_event(event)
  File "/Users/jaba/devel/aish3/gui/gui.py", line 343, in handle_event
    return self.handle_keydown(event)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/jaba/devel/aish3/gui/gui.py", line 610, in handle_keydown
    oldFocusRing.focus(oldFocusRing.get_focus())
  File "/Users/jaba/devel/aish3/gui_focus.py", line 58, in focus
    raise Exception("Control not in focus ring")
Exception: Control not in focus ring
Illegal instruction: 4

**Comment by jawa0** [comment]
Fixed in FocusRing cleanup yesterday
